FROM python:slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*

RUN pip install httpbin

EXPOSE 8000

ENTRYPOINT ["gunicorn", "-b", ":8000", "httpbin:app"]